### PR TITLE
Corrections for MDC and entry points handling.

### LINKED ISSUE #66: twTaskId MDC is needed
Logs are usually saved into ElasticSearch and indexed there.

Indexes can be more efficient, if you index the full value only (i.e. by keyword).

We currently have MDC field of `twTaskVersionId`. This however contains changing version. So by-keyword indexing will not work out as you usually don't know the version and often you want to get all logs for a particular task.

For efficiency reasons, we will split this into 2 different MDC values: `twTaskId` and `twTaskVersion`.

### PR DESCRIPTION
**Pull request by onukristo**
## Context

We need to separate MDC value of twTaskVersionId to twTaskId and twTaskVersion, so we can use more efficient ElasticSearch indexing.

MDCs are also not set consistently everywhere, let's unify that as well.

EntryPoints creating and handling needs better consistency as well.

closes #66 

### Changes

MDC corrections.
EntryPoints corrections.
NewRelic traces are removed, because TwContext will create those by itself.

## Checklist
- [ ] I have considered the impact of this change and added a [Change Classification](
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
- [ ] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

File: tw-tasks-core/src/main/java/com/transferwise/tasks/entrypoints/MdcService.java [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+import lombok.NonNull;
+import org.slf4j.MDC;
+import org.springframework.beans.factory.annotation.Autowired;
+
+public class MdcService implements IMdcService {
+
+  private static final ThreadLocal<Set<String>> keysSet = new ThreadLocal<>();
+
+  @Autowired
+  private TasksProperties tasksProperties;
```
Comment (yevhenii0) [inline tw-tasks-core/src/main/java/com/transferwise/tasks/entrypoints/MdcService.java:23]: Since only MDC is used from the properties maybe worth using it instead so that we don't need to call getter every time

**Review by yevhenii0 — APPROVED** [review]

File: tw-tasks-core/src/main/java/com/transferwise/tasks/entrypoints/MdcService.java (hunk 1 above)
Comment (onukristo) [reply tw-tasks-core/src/main/java/com/transferwise/tasks/entrypoints/MdcService.java:23]: I thought about it as well. But I think JIT is taking care of that and will inline it at one point anyway.
