### PR TITLE
pass AdminClientConfig.client-id as empty so kafka will generate auto…

### LINKED ISSUE #73: Partitions manager's Kafka admin client is sometimes complaining about MBean registration.
For example:
```
javax.management.InstanceAlreadyExistsException: kafka.admin.client:type=app-info,id=service777dd964c7bqknc (Most recent call first)
at com.sun.jmx.mbeanserver.Repository.addMBean (Repository.java:436)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository (DefaultMBeanServerInterceptor.java:1855)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean (DefaultMBeanServerInterceptor.java:955)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject (DefaultMBeanServerInterceptor.java:890)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean (DefaultMBeanServerInterceptor.java:320)
at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean (JmxMBeanServer.java:522)
at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo (AppInfoParser.java:64)
at org.apache.kafka.clients.admin.KafkaAdminClient.<init> (KafkaAdminClient.java:529)
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal (KafkaAdminClient.java:472)
at org.apache.kafka.clients.admin.Admin.create (Admin.java:71)
at org.apache.kafka.clients.admin.AdminClient.create (AdminClient.java:49)
at com.transferwise.tasks.helpers.kafka.NoOpTopicPartitionsManager.lambda$setPartitionsCount$0 (NoOpTopicPartitionsManager.java:27)
```

Lets make sure, that AdminClient will have a unique custom id to avoid that.

### PR DESCRIPTION
**Pull request by louay-mohamed**
…-incremented id

## Context

Resolves #73 

### Changes

When creating the AdminClient, we build the AdminClientConfig from the produce one, which pass the client-id, as we create as a transient class and close it immediately, we can pass the client-id here as empty then kafka will generate auto-increment id for it see https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L437

## Checklist
- [x] I have considered the impact of this change and added a [Change Classification](
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

File: tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java [hunk 1]
```diff
@@ -31,7 +33,9 @@
   @Override
   public void setPartitionsCount(String topic, int partitionsCount) {
     ExceptionUtils.doUnchecked(() -> {
-      AdminClient adminClient = AdminClient.create(kafkaConfiguration.getKafkaProperties().buildAdminProperties());
+      Map<String, Object> adminConfig = kafkaConfiguration.getKafkaProperties().buildAdminProperties();
+      adminConfig.put(AdminClientConfig.CLIENT_ID_CONFIG, "");
+      AdminClient adminClient = AdminClient.create(adminConfig);
```
Comment (lkokhreidze) [inline tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java:38]: admin client implement auto closable. If you need to use it only in this method, you'd need to close the admin client when job is done

Comment (onukristo) [reply tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java:38]: yep, we do close the client as well. But this code can also be called in parallel.

File: tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java [hunk 2]
```diff
@@ -31,7 +33,9 @@
   @Override
   public void setPartitionsCount(String topic, int partitionsCount) {
     ExceptionUtils.doUnchecked(() -> {
-      AdminClient adminClient = AdminClient.create(kafkaConfiguration.getKafkaProperties().buildAdminProperties());
+      Map<String, Object> adminConfig = kafkaConfiguration.getKafkaProperties().buildAdminProperties();
+      adminConfig.put(AdminClientConfig.CLIENT_ID_CONFIG, "");
```
Comment (robinp-tw) [inline tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java:37]: Please add comment here for purpose. Even after reading PR description, this looks pretty obscure. And future readers likely won't take the time to dig up & read the PR desc.

Could also point to the id-generator utility, to which this seemingly has some relation?

File: tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java (hunk 1 above)
Comment (louay-mohamed) [reply tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java:38]: called in parallel should be safe as if we pass empty they use atomicInteger so should be safe.

File: tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java (hunk 2 above)
Comment (louay-mohamed) [reply tw-tasks-core/src/main/java/com/transferwise/tasks/helpers/kafka/AdminClientTopicPartitionsManager.java:39]: added comments to make things clear.

**Review by onukristo — APPROVED** [review]
